// Count colors in a given texture

#pragma kernel clear_result
#pragma kernel count

Texture2D source;
RWTexture3D<uint> result;

[numthreads(8, 8, 1)]
void count (uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    source.GetDimensions(width, height);
    
    if (id.x >= width || id.y >= height) return;
    
    float4 color = source.Load(int3(id.xy, 0));
    uint3 color255 = (uint3)round(color.rgb * 255.0f);
    
    InterlockedAdd(result[color255.xyz], 1);
}

[numthreads(8, 8, 8)]
void clear_result(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= 256 || id.y >= 256 || id.z >= 256) return;
    result[id] = 0;
}